apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hjd-tls
spec:
  secretName: hejiangda-top-tls
  commonName: hejiangda-top
  dnsNames:
  - hejiangda.top
  - "*.hejiangda.top"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
