apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hejiangda-top-tls4
spec:
  secretName: hejiangda-top-tls4
  commonName: hejiangda.top
  dnsNames:
    - hejiangda.top
    - "*.hejiangda.top"
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
